title = "Tinder Call Girls Gurgaon"
baseURL = "https://www.ncrescorts.com"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 1
    name = "Models"
    url = "/models"
#  [[menu.header]]
#    weight = 3
#    name = "Blog"
#    url = "/blog"
  [[menu.header]]
    weight = 2
    name = "Rates"
    url = "/rates"
  [[menu.header]]
    weight = 3
    name = "Contact"
    url = "/contact"
  [[menu.header]]
    weight = 5
    name = "FAQs"
    url = "/faqs"


  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Tinder High-class Escort"
    subtitle = """Tinder High-class Escort welcomes you in the world of sophisticated sensuality!
    Since many years, our renowned escort agency is considered the top address for distinguished gentlemen
    who wish to treat themselves to a top-class escort service in the Indian capital. Our ladies embody everything
    the cosmopolitan gentleman expects from a perfect lady companion – both, on a sensual and on an interpersonal level.
    From the first contact to the last kiss of your dream escort Gurgaon, you can always rely on the unconditional
    discretion of our agency. We hope you enjoy the most luxurious escort services that Delhi-NCR has to offer."""

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    paragraph = """Our definition of high class escorts in Delhi-NCR starts already with the preselected choice of beautiful girls presented on our homepage. The ladies at Tinder High-class Escort are all perfectly speak English. Take a look at the profiles of our escort girls and you will be spoilt for choice. For whomever of these call girls you finally decide: Thanks to our fine preselection you will enjoy some wonderful and erotic hours. We guarantee our customers, that all photos and descriptions in the profiles of our escorts are real and honest.
                Gladly we will take the time to give you advice and answer all your questions about our Tinder escorts. This consulting may be interesting, as our call girls are all highly individual and fascinating personalities. Although each of our berlin escorts is extraordinary special on their own, they all have one thing in common: They will make you pleased and happy and let you never forget your visit in the Indian capital"""

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We believe in great service and satisfaction"
    content = "This escorts agency site will help you experience new erotic experiences with very attractive call girls. The agency Tinder High-class Escort Delhi-NCR, shows you really interesting and above all very erotic content. You will also like what you will read. Do not you sometimes just feel like a man and do not want to meet a noble whore very quickly, who can help you with their services? a there is that and the internet helps you to find the really good women in Berlin. Maybe an exotic beauty that feels soft and cuddly. Escorts models can really enrich the life and, above all, women can also fulfill the essentials in a very uncomplicated manner. Here you get the confirmation that this is available and you can easily fulfill this desire on the Internet. You just have to look closely and you will find that it will really pay off for you."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "We make the nights a delight experience to remember forever."
    paragraph = """Our escort models are the fine selection based on the satisfaction they provide to the clients.
    They are selected on the feedback from out clients we get regularly after every service. It is the
    trademark of our quality maintenance that we are the most trustable escort service in Delhi-NCR"""

  [params.contact]
    enable = true
    title = "WhatsApp on +919958003251"
    subtitle = "Call us, we will arrange everything at your comfort."
    [params.contact.box]
      phone = "Phone: +919958003251"
